<?php
/**
 * Extend Warranty
 *
 * @author      Extend Magento Team <magento@guidance.com>
 * @category    Extend
 * @package     Warranty
 * @copyright   Copyright (c) 2021 Extend Inc. (https://www.extend.com/)
 */

/** @var Extend\Warranty\Block\System\Config\Intro $block */
$moduleVersion = $block->getVersionTag();
?>

<div class="extend__intro">
    <img id="extend-logo"
         src="<?= /* @noEscape */ $block->getViewFileUrl('Extend_Warranty::images/Extend_logo_slogan.svg'); ?>"
         alt="Logo Image">
    <div class="extend__info">
        <p id="extend-intro">
            Extend generates new revenue for your store, increases overall purchase
            conversions, and provides customers with streamlined product protection and peace of mind.</p>
        <p><a href="https://extend.com/merchants">Learn more</a></p>
        <?php if (!empty($moduleVersion)): ?>
            <br />
            <strong>Ver. <?= /* @noEscape */ $moduleVersion ?></strong>
        <?php endif; ?>
    </div>
    <img id="extend-mobile"
         src="<?= /* @noEscape */ $block->getViewFileUrl('Extend_Warranty::images/mobile-offer.svg'); ?>"
         alt="Mobile Image">
</div>
