--- 
apiVersion: batch/v1
kind: CronJob
metadata: 
  name: CronJobschedule
spec:
  schedule: '* * * * *'
  jobTemplate:
    metadata: 
      name: cronjobmultipletime
    spec:
      backoffLimit: 5
      template:   
        metadata:
          name: joblive
        spec:
          restartPolicy: OnFailure
          containers:
            - name: nginx
              image: nginx 
              command: 
                - 'sleep'
                - '20s' 
