--- 
apiVersion: batch/v1
kind: Job
metadata:
  name: jobspecific
spec: 
  backoffLimit: 4
  template: 
    metadata:
      name: jobonetime
    spec:
      restartPolicy: OnFailure
      containers: 
        - name: alpine
          image: alpine
          ports:
            - containerPort: 80
              protocol: TCP  