--- 
apiVersion: apps/v1
kind: 	Deployment
metadata:
  name: db-deploy
  labels:
    app: db
    namespace: my-namespace
spec: 
  minReadySeconds: 10
  replicas: 1
  selector:
    matchlabels: 
      app: db
    matchExpressions:
      - key: environment
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25 
      maxUnavailable: 25   
  template:
    metadata:
      name: db-pod
      labels:
      app: db
    spec:
      containers: 
        - name: db-container
          image: postgres:15
          port: 
        - containerPort: 5432
          protocol: TCP 

--- 
apiVersion: v1
kind: Service
metadata:
  name: db-svc
spec:
  selector: redis
  type: clusterIP
  ports: 
    - name: db-port
      port: 5432
      targetPort: 5432
      protocol: TCP 


   
