--- 
apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc
spec: 
  minReadySeconds: 3
  replicas: 5
  selector:
    matchlevel:
      app: nginx
template: 
  metadata:
    name: nginx-pod
    labels:
      app: nginx  
      ver: "1.23"
  spec:
    containers:
      - name: nginx
        image: nginx:1.23
        ports:
          - containerPorts: 80
        protocol: TCP    
     
     
             
  
          
