--- 
apiVersion: apps/v1
kind: 	Deployment
metadata:
  name: saleor-deploy
  labels:
    app: saleor
    namespace: my-namespace
spec: 
  minReadySeconds: 5
  replicas: 1
  selector:
    matchlabels: 
      app: saleor
    matchExpressions:
      - key: environment
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25 
      maxUnavailable: 25   
  template:
    metadata:
      name: saleor-pod
      labels:
      app: saleor
  spec:
    containers: 
      - name: saleor-container
        image: satyabrata36/saleor:DEV
        port: 
          - containerPort: 8000
            protocol: TCP 

--- 
apiVersion: v1
kind: Service
metadata:
  name: saleor-svc
spec:
  selector: saleor
  type: LoadBalancer
  ports: 
    - name: saleor-port
      targetPort: 8000
      protocol: TCP 


   
