<?php
/**
 * Extend Warranty
 *
 * @author      Extend Magento Team <magento@guidance.com>
 * @category    Extend
 * @package     Warranty
 * @copyright   Copyright (c) 2021 Extend Inc. (https://www.extend.com/)
 */


/** @var \Extend\Warranty\Block\Adminhtml\Order\View\Items\Renderer\LeadOfferRenderer $block */
/** @var Extend\Warranty\ViewModel\Warranty $viewModel */
$viewModel = $block->getViewModel();
$item = $block->getItem();
$leadToken = $viewModel->getLeadToken($item);
$warrantyUniqueID = 'order' . $item->getOrderId() . '-' . $item->getId();
?>


<td>
    <?php if (!empty($leadToken)): ?>
        <div class="product-lead-token-block">
            <span><?= $block->escapeHtml(__('Lead Token'))?>: </span>
            <span><?= $block->escapeHtml(implode(',', $leadToken)) ?></span>
        </div>
    <?php endif; ?>
    <div id="extend-offer-<?= $block->escapeHtmlAttr($warrantyUniqueID) ?>"></div>
</td>

<?php if ($viewModel->showLeadOffer($item)):?>
    <script>
        require(['jquery',
                'mage/url',
                'Magento_Ui/js/modal/alert',
                'domReady!'
            ], function($, urlBuilder, alert) {
            const $elem = $('#extend-offer-<?= $block->escapeHtmlAttr($warrantyUniqueID) ?>');
            Extend.buttons.renderSimpleOffer($elem.get(0), {
                referenceId: '<?= /* @noEscape */ $viewModel->getProductSkuByOrderItem($item) ?>',
                onAddToCart: function (opts) {

                    const plan = opts.plan;
                    if (plan) {
                        let url      = "<?= /* @noEscape */ $block->getUrl('extend/warranty/leads') ?>";
                        let leadToken = "<?= /* @noEscape */ implode(", ", $leadToken); ?>";
                        let order = "<?= /* @noEscape */ $block->getOrder()->getId();?>";
                        let qty = "<?= /* @noEscape */ $viewModel->getLeftLeadsQty($item); ?>";
                        plan.product = '<?= /* @noEscape */ $viewModel->getProductSkuByOrderItem($item) ?>';
                        plan.qty = '<?= /* @noEscape */ $viewModel->getLeftLeadsQty($item); ?>';

                        $.post(url, {
                            order: order,
                            warranty: plan,
                            qty: qty,
                            leadToken : leadToken
                        }).done(function (data) {
                            if (data.status == "success") {

                                var url = data.redirect;
                                window.location.href = url;
                            } else {
                                alert({
                                    content: data.error
                                });
                            }
                        });
                    }
                }
            });

            let updateTimer = window.setInterval(() => {
                const iframe = $elem.find('iframe:visible').get(0);
                const iframeDoc = iframe ? (iframe.contentDocument || iframe.contentWindow.document) : null;

                if (iframeDoc && iframeDoc.readyState === 'complete') {
                    window.clearInterval(updateTimer);
                    window.dispatchEvent(new Event('resize'));
                }
            }, 100);
        });
    </script>
<?php endif; ?>
