<?php
/**
 * Extend Warranty
 *
 * @author      Extend Magento Team <magento@guidance.com>
 * @category    Extend
 * @package     Warranty
 * @copyright   Copyright (c) 2021 Extend Inc. (https://www.extend.com/)
 */
/** @var \Extend\Warranty\Block\Adminhtml\Order\Create\Installation $block */
/** @var \Extend\Warranty\ViewModel\Installation $viewModel */
$viewModel = $block->getData('viewModel');
$currentStoreId = $block->getCurrentStore();
?>

<?php if ($viewModel->isExtendEnabled($currentStoreId)): ?>
    <?php $jsonConfig = $viewModel->getJsonConfig($currentStoreId); ?>
    <?php if ($jsonConfig): ?>
        <script>
            Extend.config(<?=/* @noEscape */ $viewModel->getJsonConfig($currentStoreId) ?>);
        </script>
    <?php endif; ?>
<?php endif; ?>