--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
spec: 
  minReadySeconds: 5
  replicas: 3
  selector:
    matchLabels: 
      app: nginx
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template: 
    metadata: 
      name: nginx-deploy
      labels:
        app: nginx
        ver: 3.4
    spec:
      containers: 
        - name: nginx
          image: nginx:1.23
          ports: 
            - containerPorts: 80
              protocol: TCP 
          livenessProbe:
            tcpSocket:
            port: 8080 
          readinessProbe:
            httpGet:
              path: /
              port: 80
--- 
apiVersion: v1
kind: apps/v1
metadata:
  name: nginx-svc-loadbalaencer
spec: 
  type: loadblancer
  selector: 
    app: nginx
  ports: 
   - name: web-port
     port: 35000
     target-port: 80    

--- 
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-hpa
spec:
  maxReplicas: 10
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-deploy
  metrics:
    type: Reaources
    resource: 
      name: cpu 
      target: 
        averageUtilization: 70
        type: Utilization


      