--- 
apiVersion: v1
kind: Pod
metadata:
  name: pod-mysql
  namespace: my-namespace
spec:
  containers:
    - name: my-sql
      image: mysql:8
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: rootroot
        - name: MYSQL_DATABASE
          value: employees
        - name: MYSQL_USER
          value: qtdevops
        - name: MYSQL_PASSWORD
          value: qtdevops
      ports:
        - containerPort: 3306  
          protocol: TCP  
      volumeMounts:
        - mountPath: "/var/lib/mysql"
          name: mysql-data
  volume: 
    - name: mysql 
      persistentVolumeClaim: 
         claimName: mysql-aws-claim

--- 
apiVersion: v1
kind: PersistentVolume
metadata:
  name: block-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce

