<?php
/**
 * Extend Warranty - "Add Warranty" button for Lead Order
 *
 * @author      Extend Magento Team <magento@guidance.com>
 * @category    Extend
 * @package     Extend_Warranty
 * @copyright   Copyright (c) 2022 Extend Inc. (https://www.extend.com/)
 */
/**
 * @var \Extend\Warranty\Block\Order\Item\Renderer\LeadOfferRenderer $block
 */

/** @var \Magento\Sales\Api\Data\OrderItemInterface $_item */
$_item = $block->getItem();

/** @var \Extend\Warranty\ViewModel\Warranty $viewModel */
$viewModel = $block->getViewModel();

$leadToken = $viewModel->getLeadToken($_item);
?>

<div class="order-warranty-offers" id="warranty-offers-<?= $block->escapeHtmlAttr($_item->getId()) ?>"></div>
<script type="text/x-magento-init">
    {
        "#warranty-offers-<?= $block->escapeHtmlAttr($_item->getId()) ?>": {
            "leadOrderWarranty":{
                "itemId": "<?= $block->escapeJs($_item->getId()) ?>",
                "productSku": "<?= $block->escapeJs($viewModel->getProductSkuByOrderItem($_item)) ?>",
                "qty": "<?= $block->escapeJs($_item->getQtyOrdered()) ?>",
                "leadToken": "<?= $block->escapeJs(implode(", ", $leadToken)) ?>",
                "addLeadUrl" : "<?= $block->escapeUrl($block->getUrl('warranty/cart/addlead')) ?>",
                "buttonEnabled": true,
                "trackingEnabled": <?= $block->escapeJs($viewModel->isTrackingEnabled() ? 1 : 0) ?>,
                "isWarrantyInLaterOrders": <?= (int)$viewModel->isWarrantyInLaterOrders($_item) ?>,
                "isWarrantyInQuote": <?= (int)$viewModel->itemHasLeadWarrantyInQuote($_item) ?>
            }
        }
    }
</script>
