--- 
apiVersion: v1
kind: Pod
metadata:
  name: init-cont-1
  labels:
    app: nginx
spec:
  initContainers:
    - name: nginx1
      image: nginx:1.23
      ports:
        - containersPort : 80
          protocol: TCP
      command:
        - sleep
        - "30"    
  
    - name: nginx2
      image: nginx:1.24
      ports:
        - containersPort : 80
          protocol: TCP 
      command:
        - sleep
        - "30"    
  container: 
    - name: alpine
      image: alpine:1.0
      ports:
        - containersPort: 80
          protocol: TCP        
